FROM rust:1.85 AS builder

RUN curl -L https://sp1up.succinct.xyz | bash
RUN /root/.sp1/bin/sp1up 

WORKDIR /app
COPY ./contracts/ ./contracts
COPY ./server ./server
COPY ./elf ./elf
COPY Cargo.toml . 
COPY Cargo.lock .

RUN cargo build --bin server --bin autoprover --release

# RUNNER
FROM rust:1.85

WORKDIR /app

COPY --from=builder /app/target/release/server ./
COPY --from=builder /app/target/release/autoprover ./

EXPOSE 4008

CMD ["./server"]
