id = "hyligotchi"
log_format = "full"

data_directory = "data"
da_read_from = "127.0.0.1:4141"

rest_server_port = 4008
rest_server_max_body_size = 10_485_760 # 10 MB
node_url = "http://localhost:4321"
indexer_url = "http://localhost:4321"

prover = true

buffer_blocks = 0
max_txs_per_proof = 20
tx_working_window_size = 100
tick_interval_secs = 3600 # tick every hour


[websocket]
port = 8081
ws_path = "/ws"
health_path = "/ws_health"
peer_check_interval.secs = 0
peer_check_interval.nanos = 100_000_000
